apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::554007668431:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1D3GK9BOI06CX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build        
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-19T13:57:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1567"
  uid: b66f8904-d96e-4c63-8264-520b405433f5
